# 云原生构建配置文件（.cnb.yml）
# 触发条件：main分支push事件时启动构建

main: # 主分支配置
  push: # 触发事件：push到main分支
    - name: "node22-build-and-deploy" # 构建任务名称（可自定义）
      stages: # 阶段任务列表
        # 阶段1：安装依赖（用Node22镜像）
        - name: "install-deps"
          image: node:22 # 执行环境指定Node22镜像
          script: npm install # 安装项目依赖

        # 阶段2：构建项目（假设用Next.js，默认输出dist）
        - name: "build-project"
          image: node:22
          script: npm run build # 执行构建命令（根据项目调整，比如next build）

        # 阶段3：准备部署文件（复制dist到临时目录，Edgeone可能需要）
        - name: "prepare-deploy"
          image: node:22
          script: |
            mkdir -p /tmp/dist # 创建临时目录
            cp -r ./dist/* /tmp/dist/ # 复制dist内容到临时目录（根据项目调整路径）

        # 阶段4：部署到Edgeone（关键！）
        - name: "deploy-to-edgeone"
          image: tencentcom/deploy-eopages:latest # Edgeone官方部署镜像
          script: edgeone pages deploy /tmp/dist # 部署临时目录（和部署命令路径一致）
          env: # 环境变量（可选，按需添加）
            EDGEONE_SECRET: 3i/00ncAarqSnfhyQGuC7vXdhS9n8dtJE1vlSjtx1Wg= # 从密钥仓库获取的EO Secret（更安全！）